spring.application.name=week-06-Testing
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=false

#connecting to database-mySQL
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=Yashwanth@123
#enabling data.sql to run

my.variable=dev