spring.application.name=week-06-Testing


#connecting to database-mySQL
spring.datasource.url=jdbc:postgresql://localhost:5432/dev
spring.datasource.username=postgres
spring.datasource.password=Yashwanth@123

spring.flyway.enabled=false

#enabling data.sql to run
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=false


my.variable=dev