spring.application.name=inventory-service


server.servlet.context-path=/api/v1
server.port=9010

#connecting to database-mySQL
spring.datasource.url=jdbc:postgresql://${DB_HOST_URL}:5432/${DB_NAME}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

#enabling data.sql to run
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=false

spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always
spring.sql.init.data-locations=classpath:data.sql


#To get Json response in same order as we create the DTO
spring.jackson.mapper.sort-properties-alphabetically=false