spring.application.name=week-04-prod-ready-features

spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=false

#spring.datasource.url=jdbc:postgresql://localhost:5432/hospitalDB
#spring.datasource.username=postgres
#spring.datasource.password=Yashwanth@123

#connecting to database-mySQL
spring.datasource.url=jdbc:mysql://localhost:3306/prod-ready-feature?useSSL=false
spring.datasource.username=root
spring.datasource.password=Yashwanth@123

#enabling data.sql to run
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always
#spring.sql.init.data-locations=classpath:data.sql

server.port=9000

employeeService.base.url = http://localhost:8080/


#logging Configuration
logging.level.root=INFO
logging.level.com.codingshuttle.prod_ready_features.client=TRACE
logging.pattern.console=%d [%level] [%c{2.}] --- %m%n
logging.file.name=classpath:logback-spring.xml
