CREATE TABLE employee (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(255),
    email VARCHAR(255),
    age INTEGER,
    role VARCHAR(255),
    salary DOUBLE PRECISION,
    date_of_joining DATE,
    is_active BOOLEAN,
    CONSTRAINT pk_employee PRIMARY KEY (id)
);

ALTER TABLE employee
ADD CONSTRAINT uc_employee_email UNIQUE (email);