CREATE TABLE department (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title VARCHAR(255),
    is_active BOOLEAN,
    CONSTRAINT pk_department PRIMARY KEY (id)
);

ALTER TABLE employee
ADD COLUMN department_id BIGINT;

ALTER TABLE employee
ADD CONSTRAINT fk_employee_department
FOREIGN KEY (department_id)
REFERENCES department(id);